<a href="https://colab.research.google.com/github/BEYZAASLAN/BEYZAASLAN/blob/main/NUMPY-DENEME.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
a= [1,2,3,4]
b=[2,3,4,5]
a
b

[2, 3, 4, 5]

In [10]:
ab =[]
for i in  range(0,len(a)):
  ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [12]:
import numpy as np

In [17]:
dizi1 = np.array([1,2,3,4])
dizi2 = np.array([2,3,4,5])
dizi1*dizi2

array([ 2,  6, 12, 20])

In [19]:
import numpy as np
dizi=np.array(42)
print(dizi)

42


In [21]:
import numpy as np
dizi= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [25]:
import numpy as np
dizi= np.array([[1,2,3],[4,5,6]])
print(dizi)

[[1 2 3]
 [4 5 6]]


In [26]:
import numpy as np
dizi=([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(dizi)


[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]


In [30]:
#ndim ozelligi kac boyuta sahip oldugunu verir
import numpy as np
dizi1=np.array(42)
dizi2=np.array([1,2,3,4,5])
dizi3=np.array([[1,2,3,],[4,5,6]])
dizi4=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(dizi1.ndim)
print(dizi2.ndim)
print(dizi3.ndim)
print(dizi4.ndim)

0
1
2
3


In [32]:
import numpy as np
dizi= np.array([1,2,3,4])
print(dizi[0])

1


In [33]:
import numpy as np
dizi = np.array([1,2,3,4])
print([dizi[2]+dizi[3]])

[7]


In [35]:
import numpy as np
dizi =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('1.boyuttaki 2. eleman:',dizi[0,1])

1.boyuttaki 2. eleman: 2


In [38]:
import numpy as np
dizi=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2.boyut 5.eleman:',dizi[1,4])


2.boyut 5.eleman: 10


In [40]:
import numpy as np
dizi=np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]]])
print(dizi[0,1,2])

6


In [42]:
import numpy as np
dizi = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(dizi[0,1,2])


6


In [45]:
#diziye sondan bakmak istersek negatif degerler kullanırız

import numpy as np
dizi=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2. boyutun son elemanı:', dizi[1,-1])

2. boyutun son elemanı: 10


In [47]:
#pythonda dilimleme verilen bir indexten alınan elemanları baska bir indexe tasımaya denir
#DİLİM TANIMLAMA  [start: end]
# [start: end: step]
#start belirtilmezse 0 dır
#end belirtilmezse dizi uzunlugudur
#step belirtilmezse 1 dir


In [48]:
import numpy as np
dizi =np.array([1,2,3,4,5,6,7])
print(dizi[1:5:2])

[2 4]


In [50]:
import numpy as np
dizi=np.array([1,2,3,4,5,6,7])
print(dizi[::2])

[1 3 5 7]


In [52]:
import numpy as np
dizi=np.array([1,2,3,4,5,6,7])
print(dizi[1:5])

[2 3 4 5]


In [53]:
import numpy as np
dizi =np.array([1,2,3,4,5,6,7])
print([dizi[4::]])


[array([5, 6, 7])]


In [54]:
import numpy as np
dizi=np.array([1,2,3,4,5,6,7])
print(dizi[-3:-1])

[5 6]


In [56]:
import numpy as np
dizi=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print ([dizi[1,1:4]])

[array([7, 8, 9])]


In [57]:
import numpy as np
dizi=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print([dizi[0:2,2]]) #ilk iki satırı sec demek bu  bu satırların 2. indislisini cagır


[array([3, 8])]


In [59]:
#copy: yeni bir dizi , burdaki degisiklik orjinaı etkilemez orjinaldekide bunu baglamaz
#view : orjinal dizinin bir görünümü  burda etki var iki taraflı
import numpy as np
dizi=np.array([1,2,3,4])
print(dizi.dtype)


int64


In [60]:
import numpy as np
dizi=np.array([1,2,3,4],dtype='i2')
print(dizi)
print(dizi.dtype)

[1 2 3 4]
int16


In [62]:
import numpy as np
dizi =np.array([1,2,3,4,5])
x=dizi.copy()
dizi[0]=42
print(dizi)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [63]:
import numpy as np
dizi=np.array([1,2,3,4,5])
x=dizi.view()
dizi[0]=42
print(dizi)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [64]:
#Numpy da shape ozelligi
#shape: şekil ,biçim
#shape: tuple dondurur
import numpy as np
dizi=np.array([[1,2,3,4],[5,6,7,8]])
print(dizi.shape)# dizinin sekli yani kac boyutta old
#(2, 4) birinci boyutta iki eleman ikinci boyutta 4 eleman var demek bu



(2, 4)


In [66]:
#RESHAPE dizi biçimimizi değiştirmemizi sağlar   ELEMAN SAYISI UYGUN OLMALI
#normalde shape tuple dı degstiremezdik
import numpy as np
dizi=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=dizi.reshape(4,3) #4 dizi 3 elemanı olan yazdırcak
print(x)
print(dizi.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(12,)


In [68]:
import numpy as np
dizi=np.array([1,2,3,4,5,6,7,8,9,10,11])
x=dizi.reshape(4,3)
print(x)

ValueError: cannot reshape array of size 11 into shape (4,3)

In [69]:
import numpy as np
dizi=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=dizi.reshape(2,3,2)
print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [70]:
import numpy as np
dizi=np.array([1,2,3,4,5,6,7,8])
x=dizi.reshape(2,2,-1)       #BURAYI SOR ????
print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [71]:
#İTERAYON: elemanlardan tek tek gecmke anlamına geliyo
import numpy as np
dizi=np.array([1,2,3])
for x in dizi:
  print(x)

1
2
3


In [72]:
import numpy as np
dizi= np.array([[1,2,3],[4,5,6]])
for x in dizi:
  print(x)

[1 2 3]
[4 5 6]


In [75]:
import numpy as np
dizi=np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,10]]])
for x in dizi:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 5  6  7]
 [ 8  9 10]]


In [76]:
import numpy as np
dizi=np.array([[1,2,3],[4,5,6]])
for x in dizi:
  for y in x :
    print(y)       #3 boyuttada z eklersin yapmaya gerek yok

1
2
3
4
5
6


In [77]:
#İTERAYON: elemanlardan tek tek gecmke anlamına geliyo cok karmasık iterasyonlar olunca basitlessin diye
#nditer() yardımcı fonk kullanılıyo karmasık iterasyonlarda
import numpy as np
dizi=np.array([[[1,2],[3,4],[5,6],[7,8]]])
for x in np.nditer(dizi):
  print(x)

1
2
3
4
5
6
7
8


In [82]:
#farklı basamak belirterek iterasyon
import numpy as np
dizi = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(dizi[:, ::2]):  # step 2 : Bu ifade, tüm satırları seçer::2: Bu ifade, sütunlarda ikişer ikişer atlayarak elemanları seçer.
  print(x)

1
3
5
7


In [83]:
#Bazen sıralamak için  elemanın karsılık geldıgı ındex lazım olur
#NDENUMERATE() kullanılır


In [85]:
#JOIN birleştirme işlemi demek
#concatenate() ile birlestirilir  ingde birlestırmek demek zaten
import numpy as np
dizi1 = np.array([1,2,3])
dizi2 = np.array([4,5,6])
dizi = np.concatenate((dizi1,dizi2)) # 2 parantez old unutma
print(dizi)

[1 2 3 4 5 6]


In [86]:
import numpy as np
dizi1= np.array([[1,2],[3,4]])
dizi2= np.array([[5,6],[7,8]])
dizi= np.concatenate((dizi1,dizi2))
print(dizi)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [87]:
import numpy as np
dizi1= np.array([[1,2],[3,4]])
dizi2= np.array([[5,6],[7,8]])
dizi= np.concatenate((dizi1,dizi2), axis=1)
print(dizi)

[[1 2 5 6]
 [3 4 7 8]]


In [88]:
#SPLİT parcalamak ayırmak demek
import numpy as np
dizi=np.array([1,2,3,4,5,6])
x=np.array_split(dizi,3) #3 dizi içericek artık
print(x)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [90]:
import numpy as np
dizi=np.array([1,2,3,4,5,6])
x=np.array_split(dizi,3)
print(x[0])
print(x[2])

[1 2]
[5 6]


In [91]:
#WHERE :   degeri dizide arar  index değerini tuple içinde dondurur
import numpy as np
dizi= np.array([1,2,3,4,5,4,4])
x=np.where(dizi==4)     #(array([3, 5, 6]),)  index yeri bunlarr
print(x)

(array([3, 5, 6]),)


In [92]:
import numpy as np
dizi= np.array([1,2,3,4,5,6,7,8])
x=np.where(dizi%2==0)
print(x)

(array([1, 3, 5, 7]),)


In [96]:
import numpy as np
dizi=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
x=np.array_split(dizi,3 ,axis=1)
print(x)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [98]:
#sort sıralama  :  azalan artan orjinal dizi degismez copy degisir
import numpy as np
dizi=np.array([3,2,0,1])
print(np.sort(dizi)[::-1])  #[::-1]  azalan sekilde sıralasın diye

[3 2 1 0]


In [100]:
import numpy as np
dizi= np.array(['airaz','bortakal','çilek','clma'])
print(np.sort(dizi))

['airaz' 'bortakal' 'clma' 'çilek']


In [101]:
import numpy as np
dizi= np.array([[3,2,4],[5,0,1]])
print(np.sort(dizi))

[[2 3 4]
 [0 1 5]]


In [104]:
#FİLTRELEME: diziden bazı elemanları alıp yeni dzi yaparsam filtreleme olur
#boolean İNDEX list kullanılıyo
#dogruysa fıltrelenıs dızıde olur deılse filrelenmis diziden cıkar
import numpy as np
dizi=np.array([41,42,43,44])
x=[True,False,True,True]
filtre=dizi[x]
print(filtre)

[41 43 44]


In [107]:
#Filtre dizisi olusturma
import numpy as np
dizi=np.array([41,42,43,44])
x=dizi>42
filtre=dizi[x]
print(x)
print(filtre)


[False False  True  True]
[43 44]


In [111]:
#rastgele sayı için randint() meetodu kullanılır
from numpy import random
x= random.randint(100)
print(x)

27


In [114]:
from numpy import random
x=random.rand() #float tipinde olsun diye
print(x)

0.29013619812717306


In [119]:
#Diziden ratgele sayı olusturma
#choice() metodu : diziyi alcak ratgele dondurcek bi degeri
from numpy import random
x= random.choice([3,5,7,9])
print(x)


7


In [120]:
from numpy import random
x= random.choice([3,5,7,9],size=(3,5)) #3 satır 5 sutun yanı
print(x)


[[5 9 3 3 3]
 [5 5 9 7 9]
 [7 7 7 9 9]]


In [122]:
from numpy import random
x=random.randint(100,size=(5))
print(x)

[55 33  2 63 36]


In [123]:
#Normal (gaussian) dagılım
#normal() metodu
#verilen deger etrafında rastgele deger
#loc:ort(can tepe nokt)
#scale: standart sapma
#size:dizinin boyutu

In [125]:
#shuffle() dizi elemanları yerleşim duzeni
#orjinal dizi degisir
from numpy import random
import numpy as np
dizi=np.array([1,2,3,4,5])
random.shuffle(dizi)
print(dizi)

[3 2 5 4 1]


In [126]:
from numpy import random
x= random.normal(loc=5,scale=2,size=(3,5))
print(x)

[[4.13559079 4.26549634 4.09306547 6.45877586 3.78246478]
 [5.77011282 3.28340703 4.87057236 4.29826215 5.06741805]
 [5.63260493 6.39886604 1.12162617 6.77907113 3.82481068]]
